# Site settings
title: Igor Octaviano
email: igoroctaviano@gmail.com
twitter: https://twitter.com/igoroctaviano
description: > # this means to ignore newlines until "baseurl:"
  Um blog sobre desenvolvimento e tecnologias.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://igoroctaviano.com.br/blog" # the base hostname & protocol for your site
github_username: igoroctaviano
twitter_username: igoroctaviano

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
